---
scheduler_plugins_controller_replicas: 1

# Global gate to enable or disable scheduler plugins.
scheduler_plugins_enabled: false

# List of currently supported scheduler plugins.
scheduler_plugins_supported_list:
  - CoScheduling
  - CapacityScheduling
  - NodeResources

# List of scheduler plugins to be enabled.
scheduler_plugins:
  - CoScheduling

# Path to kubeSchedulerConfiguration file.
scheduler_configuration_path: "{{ kube_config_dir }}/scheduler-config.yml"

# Additional KubeSchedulerConfiguration settings (e.g. metricsBindAddress).
kube_scheduler_config_extra_opts: {}

# List of scheduler extenders (dicts), each holding the values of how to
# communicate with the extender.
kube_scheduler_extenders: []

# Leader Election options (e.g. ResourceName, RetryPerion) except from
# LeaseDuration and Renew deadline which are defined in following vars.
kube_scheduler_leader_elect_extra_opts: {}

# Leader election lease duration
kube_scheduler_leader_elect_lease_duration: 15s

# Leader election lease timeout
kube_scheduler_leader_elect_renew_deadline: 10s

# Custom profile for enabled scheduler plugins (effect on default-scheduler).
scheduler_plugins_custom_profile: ""

# Default profile for CoScheduling (effect on default-scheduler).
scheduler_plugins_coscheduling_profile: |-
  plugins:
    preFilter:
      enabled:
      - name: CapacityScheduling
    postFilter:
      enabled:
      - name: CapacityScheduling
      disabled:
      - name: "*"
    reserve:
      enabled:
      - name: CapacityScheduling

# Default profile for CapacityScheduling (effect on default-scheduler).
scheduler_plugins_capacityscheduling_profile: |-
  plugins:
    queueSort:
      enabled:
      - name: Coscheduling
      disabled:
      - name: "*"
    preFilter:
      enabled:
      - name: Coscheduling
    postFilter:
      enabled:
      - name: Coscheduling
    permit:
      enabled:
      - name: Coscheduling
    reserve:
      enabled:
      - name: Coscheduling
  pluginConfig:
  - name: Coscheduling
    args:
      permitWaitingTimeSeconds: 10

# Default profile for NodeResources (effect on default-scheduler).
scheduler_plugins_noderesources_profile: |-
  plugins:
    score:
      enabled:
      - name: NodeResourcesAllocatable
      disabled:
      - name: "*"
  pluginConfig:
  - name: NodeResourcesAllocatable
    args:
      mode: Least
      resources:
      - name: cpu
        weight: 1000000
      - name: memory
        weight: 1